name: BloodOnTheBlocktower
version: 1.25.10-sp-alpha
main: io.github.tony12684.BotB.Main
api-version: 1.21.10
commands:
  BOTBStartGame:
    description: Starts a new game of Blood on the Blocktower
    usage: /<command>
    permission: botb.startgame
    permission-message: You do not have permission to start a game.